stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
  script:
    - scp -r ./* $SSH_USER@$DEPLOYMENT_SERVER_IP:/home/$DEPLOYMENT_SERVER_USER
    - ssh -T $SSH_USER@$DEPLOYMENT_SERVER_IP 'bash -s' < start_docker.sh $DEPLOYMENT_SERVER_USER
    #- ssh -t $SSH_USER@$DEPLOYMENT_SERVER_IP "cd home && cd $DEPLOYMENT_SERVER_USER && set -a && source odoo-variables.env && docker-compose up -d"
