version: '3'
services:  
  postgres:
    image: postgres:10.0
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  odoo:
    image: wjriedstra/odoo:12.0-dev
    command: odoo
    depends_on:
      - postgres
    ports:
      - 8071:8069
    # links:
    #   - postgres:db
    environment:
      - ODOO_ADMIN_PASSWD=strong_odoo_master_password
      - ODOO_DB_USER=odoo
      - ODOO_DB_HOST=False
    volumes:
      - odoo-data:/var/lib/odoo
    restart: always
volumes:
  odoo-data:
    driver: local