version: '3'
services:
  odoo:
    image: wjriedstra/odoo:12.0-dev
    command: odoo
#    env_file:
#      - odoo-variables.env
    ports:
      - "80:${ODOO_XMLRPC_PORT}"
      - "443:${ODOO_LONGPOLLING_PORT}"
    environment:
      - ODOO_DB_HOST=localhost
      - ODOO_DB_USER=odoo
    volumes:
      - odoo-data:/var/lib/odoo
    restart: always
    network_mode: "host"
volumes:
  odoo-data:
    driver: local