version: '3'
services:
  odoo:
    image: wjriedstra/odoo:12.0-dev
    command: odoo
    ports:
      - "80:${ODOO_XMLRPC_PORT}"
      - "443:${ODOO_LONGPOLLING_PORT}"
    environment:
      - ODOO_DB_HOST=localhost
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD
      - ODOO_ADMIN_PASSWD
      - ODOO_XMLRPC_PORT
      - ODOO_LONGPOLLING_PORT
    volumes:
      - odoo-data:/var/lib/odoo
      - ./auto_addons/oca_dependencies.txt:/opt/odoo/additional_addons/oca_dependencies.txt
    restart: always
    network_mode: "host"
volumes:
  odoo-data:
    driver: local