version: '3.3'

services:  
  postgres:
    image: postgres:10.0
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres

  odoo:
    image: wjriedstra/odoo:12.0-dev
    command: odoo
    ports:
      - 9000:8069
    links:
      - postgres:db
    environment:
      - ODOO_ADMIN_PASSWD=strong_odoo_master_password
      - ODOO_DB_USER=odoo