version: '3'
services:
  odoo:
    image: wjriedstra/odoo:12.0-dev
    command: odoo
    ports:
      - 8071:8069
    environment:
      - ODOO_DB_HOST=localhost
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_ADMIN_PASSWD=strong_odoo_master_password
    volumes:
      - odoo-data:/var/lib/odoo
    restart: always
    network_mode: "host"
volumes:
  odoo-data:
    driver: local