#!/bin/bash
{
  echo "ODOO_DB_PASSWORD=$ODOO_DB_PASSWORD"
  echo "ODOO_ADMIN_PASSWD=$ODOO_ADMIN_PASSWD"
  echo "ODOO_XMLRPC_PORT=$ODOO_XMLRPC_PORT"
  echo "ODOO_LONGPOLLING_PORT=$ODOO_LONGPOLLING_PORT"
} >> ".env"
